on: [push]

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          apt update
          apt install -y libudev-dev
          curl https://sh.rustup.rs > installer.sh
          sh ./installer.sh --default-toolchain none -y
          source "$HOME/.cargo/env"
          rustup default nightly
          cargo test
          cargo fmt --all -- --check
